name: '自动化测试'

on:
  workflow_dispatch


jobs:
  run-autotest:
    runs-on: [self-hosted, tester]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "updater: 获取版本"
        run: |
          echo "XX_APP_VERSION=14.0" >> $GITHUB_ENV

      - name: '创建python本地虚拟环境并激活'
        run: |
          python -m venv test_$XX_APP_VERSION
          

      - name: '文件复制到虚拟环境并创建依赖'
        run: |  
          robocopy 'C:\actions-runner\_work\test\test' C:\Users\admin\test_14.0 /E /COPY:DAT
#          pip install -r requirements.txt

      - name: Run test.py script and capture output
        id: run_py
        run: |
          C:\Users\admin\test_14.0\Scripts\python test.py > output.txt  
          output=$(type output.txt)  
          echo "::set-output name=script_output::$output"  

      - name: Get the output
        run: |
          echo "The report of run.py is ${{ steps.run_py.outputs.script_output }}""
