name: '自动化测试'

on:
  workflow_dispatch


jobs:
  run-autotest:
    runs-on: [self-hosted, tester]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "updater: 获取版本"
        run: |
          echo "xx_app_version=14.0" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append 

      - name: '创建python本地虚拟环境并激活'
        run: |
          $file = $Env:xx_app_version
          mkdir "c:\$file"
#           python -m venv C:\
          

#       - name: '文件复制到虚拟环境并创建依赖'
#         run: |
#           copy 'C:\actions-runner\_work\test\test\*' C:\test_14.0
# #          pip install -r requirements.txt

#       - name: Run test.py script and capture output
#         id: run_py
#         run: |
#           C:\test_14.0\Scripts\python.exe C:\test_14.0\test.py > C:\test_14.0\output.txt

#       - name: Get the output
#         run: |
#           $output = Get-Content C:\test_14.0\output.txt 
#           echo "The report of run.py is $output"
