name: '自动化测试'

on:
  workflow_dispatch


jobs:
  run-autotest:
    runs-on: [self-hosted, tester]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "updater: 获取版本"
        working-directory: packages/robot
        id: get_version
        run: |
          flutter pub get --offline
          xx_app_version='14.0'

      - name: '创建python本地虚拟环境并激活'
        run: |
          c:
          python -m venv test_${steps.get_version.xx_app_version}
          .\test_${steps.get_version.xx_app_version}\Scripts\activate
          

      - name: '文件复制到虚拟环境并创建依赖'
        run: |  
          robocopy 'C:\actions-runner\_work\xx\xx\automated\test' C:\Users\admin\test_${steps.get_version.xx_app_version} /E /COPY:DAT
#          pip install -r requirements.txt

      - name: Run test.py script and capture output
        id: run_py
        run: |
          python test.py > output.txt  
          output=$(cat output.txt)  
          echo "::set-output name=script_output::$output"  

      - name: Get the output
        run: |
          echo "The report of run.py is ${{ steps.run_py.outputs.script_output }}"
